version: '3.9'

services:
  PostSQL:
    container_name: PostSQL
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:13-alpine
  Pgadmin:
    container_name: Pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fuck@niggers.ru
      PGADMIN_DEFAULT_PASSWORD: fuck
    image: dpage/pgadmin4