#version: '3.9'

services:
  PostSQL:
    container_name: PostSQL
    restart: always
    
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    
    image: postgres:13-alpine

  
  blog:
    container_name: blog
    restart: always

    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    
    command: ./server

    environment:
      - JWT=fuck
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=db
      - DB_HOST=PostSQL
      - DB_PORT=5432

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certcache:/var/www/.cache

    depends_on:
      - PostSQL
